version: '3.8'

services:
  bot:
    build: .
    container_name: telegram-bot
    environment:
      - DB_HOST=db
      - DB_NAME=mydatabase
      - DB_USER=user
      - DB_PASSWORD=password
    depends_on:
      - db
    ports:
      - "8080:8080"

  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - ./app/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
